name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]   # Trigger pipeline on pushes to main

jobs:
  build-and-push:
    runs-on: ubuntu-latest   # GitHub-hosted runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build backend image
        run: docker build -t nikitamishra/crud-backend:latest ./backend

      - name: Build frontend image
        run: docker build -t nikitamishra/crud-frontend:latest ./frontend

      - name: Push backend image
        run: docker push nikitamishra/crud-backend:latest

      - name: Push frontend image
        run: docker push nikitamishra/crud-frontend:latest

  deploy:
    runs-on: self-hosted     # I am using WSL runner
    needs: build-and-push    # Run only after build-and-push succeeds
    steps:
      - name: Pull and restart containers
        run: |
          cd ~/crud-dd-task-mean-app
          docker compose pull
          docker compose up -d
